### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AsaMarjew** [AsaMarjew/GameBuddy#8]
### Must have
- [x] Zorgen dat eigen profiel niet zichbaar is tussen lijst met gebruikers
- [x] Fortnite img afbeelding laadt niet in op dashboard
- [x] ISSUE: too many redirects wanneer ik naar /verwijderen wil gaan
- [x] ISSUE: wanneer #filterKnop wordt aangeroepen in script.js , is een foutmelding en stopt het script ook. Dus op pagina's waar de filterknop staat, worden de FA icons niet geladen. -> Misschien toch apart bestand voor filter script?
- [x] Fallback PE favorieten
- [x] Read me aanpassen (Muhammet) 
- [x] Code comments aanpassen (Iedereen)
- [x] Code namen in engels checken (iedereen)
- [x] Email check bij aanmelden, bestaat deze al in db (Asa)
- [x] Mail verzenden na aanmelden (Asa)
- [x] Sessions implementeren in features (Iedereen)
    - [x] DB - Favorieten in gebruikers object zetten, js aanpasssen (Philip)
    - [ ] Verwijderen - User uit favorieten van alle gebruikers halen (Asa)
    - [x] Verwijderen - Alleen eigen email verwijderen (Asa)
    - [x] API - knoppen fixen (Muhammet)
- [x] Nav verwijder registreren knop (Kiara)
- [x] Nav niet klikbaar wanneer niet ingelogd (Kiara)
- [x] CSS body height -> scroll fixen (Philip)
- [x] Wiki topic (iedereen)
- [x] Wiki feature (iedereen)
- [x] Wiki - Wireframe (Muhammet)
- [x] PE toevoegen (Asa)
- [x] Wiki - Design & style sheet herschrijven (Asa)
- [x] Wiki - Meta data herschrijven (Asa)
- [x] Hover states toevoegen / fixen (Philip)
- [x] CSS p color naar class voor user card (Philip)
- [x] Homepage/hoe werkt het: plaats oproep -> Registreren (Philip)
- [x] Homepage knoppen -> inloggen en registreren (Philip)
- [x] Home (Asa)
- [x] Requirements list (Asa)
- [x] Concept (Asa)
 
### Should have
- [x] HTML werkend zonder CSS -> PE
- [ ] Fontsize favorieten empty state gelijk aan Homepage
- [x] formulier ombouwen van div naar fieldset

### Could have
- [ ] Nodemailer - mail template (Asa)
